### ISSUE TITLE
Using nonce for dst in call to Seal

### ISSUE THREAD

**Issue by jcline** [GGP1/kure#1]
Hi,

On https://github.com/GGP1/kure/blob/ad75a75514bc32646617e335844a4b7758d38deb/crypt/crypt.go#L53 it seems odd to use `nonce` as `dst` in `AEAD.Seal()`. It appears that in `Seal` `sliceForAppend` is called which increases the size of `dst` if it is not large enough for the result. If it increases the size, when it gets to the `deriveCounter` call, it will take the wrong branch and not use the intended counter calculation, see https://golang.org/src/crypto/cipher/gcm.go?s=3384:3423#L397

I'd suggest creating a new slice for dst in the call to Seal.

**Comment by GGP1** [comment]
Hi, thanks for mentioning it, I've created a new slice for dst. It will be fixed in the next release.

**Comment by GGP1** [comment]
Hi, I've created a new slice for dst. Thanks for your help.
