### ISSUE TITLE
error: invalid length

### ISSUE THREAD

**Issue by chungktran** [GGP1/kure#2]
I'm trying to use a key file and getting error `error: invalid length`. I tried x509 key file as well as just a simple hash string in a file and the same error.

**Comment by GGP1** [comment]
The error that you are receiving is not form the key file but the command you are trying to execute, if you do not specify any length when using `kure add` commands, it will return that error.

**Comment by chungktran** [comment]
Yes I figured out that was the case so I closed this issue.
