### ISSUE TITLE
How to migrate a database prior to 1.0

### ISSUE THREAD

**Issue by shuen2023** [GGP1/kure#39]
Sorry, I clicked on the database migration link in the release notes. Didn't understand how to migrate?

**Comment by GGP1** [comment]
Hi @shuen2023, to migrate the database you can download the file called `kure_v1_migration.tar.gz` from the [assets](https://github.com/GGP1/kure/releases/tag/v1.0.0) section of the `v1.0.0` release, decompress it and execute the script that comes with it. 

It will ask you for the master password and to confirm the operation, but that's all.

You can make a backup of your database by using the `kure backup` command before the migration if it gives you peace of mind.

> [!Note]
> Alternatively, if you don't trust the artifacts, you could clone the repository and execute the script locally by doing
> 
> ```console
> git clone -b v1.0.0 --single-branch https://github.com/GGP1/kure
> go get -u
> go run migration/v1/main.go
> ```

**Comment by GGP1** [comment]
Hi @shuen2023, to migrate the database you can download the file called `kure_v1_migration.tar.gz` from the [assets](https://github.com/GGP1/kure/releases/tag/v1.0.0) section of the `v1.0.0` release, decompress it and execute the script that comes with it. 

It will ask you for the master password and to confirm the operation, but that's all.

> This will encrypt all the names in the database using a XOR operation between the authentication key and each one of the names.

You can make a backup of your database by using the `kure backup` command before the migration if it gives you peace of mind.

> [!Note]
> Alternatively, if you don't trust the artifacts, you could clone the repository and execute the script locally by doing
> 
> ```console
> git clone -b v1.0.0 --single-branch https://github.com/GGP1/kure
> go get -u
> go run migration/v1/main.go
> ```

**Comment by GGP1** [comment]
Hi @shuen2023, to migrate the database you can download the file called `kure_v1_migration.tar.gz` from the [assets](https://github.com/GGP1/kure/releases/tag/v1.0.0) section of the `v1.0.0` release, decompress it and execute the script that comes with it. 

It will ask you for the master password and to confirm the operation, but that's all.

> This will encrypt all the names in the database using a XOR operation between the authentication key and each one of the names.

You can make a backup of your database by using the `kure backup` command before the migration if it gives you peace of mind.

> [!Note]
> Alternatively, if you don't trust the artifacts, you could clone the repository and execute the script locally by doing
> 
> ```console
> git clone -b v1.0.0 --single-branch https://github.com/GGP1/kure
> go get -u
> go run migration/v1/main.go
> ```

**Comment by shuen2023** [comment]
> 你好@shuen2023要迁移数据库，您可以`kure_v1_migration.tar.gz`从发布的[资产](https://github.com/GGP1/kure/releases/tag/v1.0.0)部分下载该文件`v1.0.0`，解压缩它并执行随附的脚本。
> 
> 它会要求您输入主密码并确认操作，但仅此而已。
> 
> > 这将使用身份验证密钥和每个名称之间的 XOR 运算来加密数据库中的所有名称。
> 
> `kure backup`如果这样能让您安心，您可以在迁移之前使用该命令备份您的数据库。
> 
> 笔记
> 
> 或者，如果你不信任这些工件，你可以克隆存储库并通过执行以下操作在本地执行脚本
> 
> ```
> git clone -b v1.0.0 --single-branch https://github.com/GGP1/kure
> go get -u
> go run migration/v1/main.go
> ```

Oh, sorry I'm really stupid! I was able to migrate it. However, there is still a garbled name and I don't know how to deal with it    

![Screenshot_20240817_220849_com termux_edit_191143586218958](https://github.com/user-attachments/assets/7801415a-a276-4ac5-824a-13e671a91e4d)

**Comment by shuen2023** [comment]
I originally thought that the migration database would be included in the new version of the command. So I directly go install -v github.com/GGP1/kure@latest and then I couldn't wait to use the new version of kure to open the original database. What happened next was that I could only leave a message for help.Thank you

**Comment by shuen2023** [comment]
Oh, I remember now. I created the entry right after installing the new version. So when I migrate the database later, the password entry created with the new version may have garbled names.
