### ISSUE TITLE
Ctrl +d in kure session create a loop 

### ISSUE THREAD

**Issue by fdurand** [GGP1/kure#4]
Hello, 
I am testing Kure (really promising) under Linux (Ubuntu 20.04).
I have an issue when i try to quit the session with ctrl d, it looks that i create a loop. (the help message over and over).
Thanks

**Comment by GGP1** [comment]
Hi @fdurand, I guess I've found the issue, ctrl+d is indicating an end of file to:

```go
fmt.Printf("\n%s ", opts.prefix)
```

inside the session, which is not handling it. Changing this to: 

```go
_, err := fmt.Printf("\n%s ", opts.prefix)
```

**Comment by GGP1** [comment]
Hi @fdurand, the session was reading from `bufio.Scanner` which returned **nil** on EOF errors, I've changed it to fmt.Fscanln():

```go
_, err := fmt.Fscanln(r, &text)
if err != nil {
    if err == io.EOF {
        fmt.Print("\n")
	exit(db)
    } else {
	fmt.Fprintln(os.Stderr, "error", err)
    }
}
```

to solve this. The change will be commited as soon as possible and I might release a version v0.1.1 as well, thanks for your help.
