### ISSUE TITLE
IMPORTANT! Security Vulnerability Detected in your Repository

### ISSUE THREAD

**Issue by jessicMUaheYrnandez** [GGP1/kure#40]
Hey there!

We have detected a security vulnerability in your repository. Please contact us at https://github-scanner.com to get more information on how to fix this issue.

Best regards,
Github Security Team

**Comment by GGP1** [comment]
Hello @jessicMUaheYrnandez, if you found a security vulnerability please feel free to open a [security advisory](https://github.com/GGP1/kure/security/advisories) detailing it, no other third party websites will be used for this.
